version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
      _PIP_ADDITIONAL_REQUIREMENTS: 'duckdb pandas loguru python-dotenv dbt-core dbt-duckdb'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    volumes:
      - postgres-db:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:2.9.1
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
      _PIP_ADDITIONAL_REQUIREMENTS: 'duckdb pandas loguru python-dotenv dbt-core dbt-duckdb'
    depends_on:
      postgres:
        condition: service_healthy
    command: version
    volumes:
      - ./dags:/opt/airflow/dags
      - ../olist_analytics:/opt/airflow/olist_analytics
      - ../data:/opt/airflow/data
      - ../ingestion:/opt/airflow/ingestion
      - airflow-logs:/opt/airflow/logs

  airflow-webserver:
    image: apache/airflow:2.9.1
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      _PIP_ADDITIONAL_REQUIREMENTS: 'duckdb pandas loguru python-dotenv dbt-core dbt-duckdb'
    depends_on:
      postgres:
        condition: service_healthy
    command: webserver
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ../olist_analytics:/opt/airflow/olist_analytics
      - ../data:/opt/airflow/data
      - ../ingestion:/opt/airflow/ingestion
      - airflow-logs:/opt/airflow/logs

  airflow-scheduler:
    image: apache/airflow:2.9.1
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      _PIP_ADDITIONAL_REQUIREMENTS: 'duckdb pandas loguru python-dotenv dbt-core dbt-duckdb'
    depends_on:
      postgres:
        condition: service_healthy
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ../olist_analytics:/opt/airflow/olist_analytics
      - ../data:/opt/airflow/data
      - ../ingestion:/opt/airflow/ingestion
      - airflow-logs:/opt/airflow/logs

volumes:
  airflow-logs:
  postgres-db: